### ISSUE TITLE
Enum() fails to display the drop-down selection of Enums when it is a Sub() of a group

### ISSUE THREAD

**Issue by Symmasolan** [JasonMa0012/LWGUI#17]
When an Enum() property is the child of a drawer, the enum values do not display as expected.

For example, the following property properly nests under `Main(GroupAdv)`:
`[Enum(Off,0,On,1)] [Sub(GroupAdv)] _ZWrite ("ZWrite Mode", Float) = 1`
But the Enum property does not show the drop-down selection of enums.
![Unity_BrokenEnum_Grouped](https://user-images.githubusercontent.com/10646301/221439388-8c1e1cd3-74ab-458a-84a2-0b72bf5db09a.png)

If I instead use the following property setup:
`[Enum(Off,0,On,1)] _ZWrite ("ZWrite Mode", Float) = 1`
The ZWrite property behaves as expected and is no longer nested within the group.
![Unity_WorkingEnum_NotGrouped](https://user-images.githubusercontent.com/10646301/221439317-08ddce55-0ab6-482c-ba79-1d9d2998fffd.png)

I am using the latest release of LWGUI (v1.4.0) with Unity v2019.4.31f1.

**Comment by JasonMa0012** [comment]
You should use SubEnum():

![image](https://user-images.githubusercontent.com/39983625/221457929-ddb35d30-9219-4034-98fd-e45ce341635b.png)

```
        [Main(g1, _, on, on)] _group ("Group", float) = 1
        [SubEnum(g1, Off,0,On,1)] _ZWrite ("ZWrite Mode", Float) = 1
```
