### ISSUE TITLE
请问一下如何保存变更？

### ISSUE THREAD

**Issue by ljwlaji** [JasonMa0012/LWGUI#21]
现在情况是调整了材质之后 如果直接拷贝材质 所有的变更都会还原

**Comment by JasonMa0012** [comment]
复制之前 File > Save Project

**Comment by ljwlaji** [comment]
gsdg54sdg5s4d5gからドムをプレゼンりやかなベルガモットオジビタからロピカなフ

**Comment by ljwlaji** [comment]
不行 现在是Vector无法被保存 其他都可以
![image](https://user-images.githubusercontent.com/16899528/228780163-fc183b97-87f7-4f34-a084-3ce2261f8cd4.png)

**Comment by ljwlaji** [comment]
换成 _MainTex_ST_1可以 为什么会有这样的情况呢

**Comment by JasonMa0012** [comment]
_MainTex_ST是一个隐式默认Property Name, 你显示声明之后值会被Drawer覆盖

**Comment by ljwlaji** [comment]
好的 目前暂时这么解决了 3Q
