### ISSUE TITLE
加了Sub标签后, Enum标签无法生效

### ISSUE THREAD

**Issue by a995049470** [JasonMa0012/LWGUI#3]
![image](https://user-images.githubusercontent.com/37652153/187903840-d65c1260-f08c-4d49-a719-3c47fd0f550a.png)
![image](https://user-images.githubusercontent.com/37652153/187903866-b5c86916-94db-4b09-afed-04fabf147e2a.png)

**Comment by JasonMa0012** [comment]
使用KWEnum

**Comment by JasonMa0012** [comment]
多个Drawer只会生效一个，能够使用多次的是Decorator，比如Header，Space，Title

**Comment by a995049470** [comment]
但是KWEnum并不能像Enum那样给字段赋几个特定值..

**Comment by JasonMa0012** [comment]
尝试1.1.0
