### ISSUE TITLE
Unable to find style 'ToolbarSeachTextFieldPopup' in skin 'DarkSkin' Layout

### ISSUE THREAD

**Issue by xpc-yx** [JasonMa0012/LWGUI#34]
![image](https://github.com/JasonMa0012/LWGUI/assets/6227185/d1bbeea7-ec2c-498b-b950-7ee571d09d1f)

**Comment by xpc-yx** [comment]
最新版本一直有刷警告

**Comment by JasonMa0012** [comment]
我这没有复现, 请问用的哪个unity版本, 以及哪个LWGUI版本开始出现的问题?

**Comment by xpc-yx** [comment]
unity2022.3.4 lwgui1.8.2

**Comment by xpc-yx** [comment]
试了下1.7.0就会有这个警告

**Comment by JasonMa0012** [comment]
试一下你那边用空项目安装LWGUI会不会有警告

**Comment by JasonMa0012** [comment]
我这边以前好像出现过这个问题, 但最近怎么都无法复现

**Comment by xpc-yx** [comment]
之前也没见过这个警告 是突然更新版本后出现的
