### ISSUE TITLE
Support for ShaderGraph or ASE

### ISSUE THREAD

**Issue by Dawie3565** [JasonMa0012/LWGUI#36]
hello
this is David from Amplify support. aka Dawie 
in ASE discord someone suggested you are looking to intergrade more into ASE 
drawer files and GUI are very easy to add using ASE 

if you have any issues or trouble, feel free to contact me in the official ASE discord.
keep up the good work.

**Comment by JasonMa0012** [comment]
Thanks, I will study how to better integrate with ASE recently

**Comment by JasonMa0012** [comment]
Hi, Dawie.

I'm trying to integrate LWGUI into ASE, but I found that PropertyNode.PropertyAttributes hard-coded the generation of Attributes, and it seems that there is no feasible solution without modifying the ASE code.

I hope that the Attributes of LWGUI can be as easy to use as the ones that come with ASE. Users only need to select the required Drawers, and then enter the parameters according to the prompts.

Can you please help to realize this function? For example, abstract the code of ASE so that LWGUI can extend the generation of Attributes, or directly include LWGUI in ASE and develop it?

**Comment by Dawie3565** [comment]
Hi Jason 
reach out to me in discord so we can chat in real-time then i can show you some examples. 
look for David in the amplify discord. 

I also have a large collection of drawer files i consider adding in ASE for users to modify / use however i have not found time to do it yet. this sounds like we can collaborate for some of this.

**Comment by lokyeye** [comment]
有没有办法支持ASE的Static Switch，这个目前好像不支持！

**Comment by JasonMa0012** [comment]
ASE的Custom Drawer中填SubToggle(_, _YOUR_KEYWORD)

**Comment by lokyeye** [comment]
好像不行 我填的SubToggle(Group1, _YOUR_KEYWORD)应该没错吧

**Comment by lokyeye** [comment]
![Uploading 微信图片_20240407162347.png…]()

**Comment by JasonMa0012** [comment]
![image](https://github.com/JasonMa0012/LWGUI/assets/39983625/b3e4058e-a809-4ed8-a177-30a5b110ef90)
![image](https://github.com/JasonMa0012/LWGUI/assets/39983625/ff0a1134-c6e1-439c-899c-4e826fdd23b1)
![image](https://github.com/JasonMa0012/LWGUI/assets/39983625/42789d32-6e83-454b-be59-558d82652bf0)

- CustomEditor必须是'LWGUI.LWGUI'
- Static Switch的Name必须全大写, 如'TEST_KEYWORD', 取消Material Toggle
- 新建一个Float Parameter, 打开Auto-Register, 根据需要填写Custom Drawer, 如'SubToggle(_, _TEST_KEYWORD)', Keyword需要前置下划线

![image](https://github.com/JasonMa0012/LWGUI/assets/39983625/ecb1c308-4f75-4801-bc1d-ade1883b069a)
![image](https://github.com/JasonMa0012/LWGUI/assets/39983625/6b0507e4-b80f-4c7f-9ab8-333f1cd03669)

**Comment by lokyeye** [comment]
感谢大佬！我会把这个姿势会传出去的！！

**Comment by lokyeye** [comment]
大佬！我朋友在问static switch的Ketword Enum模式怎么弄出去呢

**Comment by JasonMa0012** [comment]
一样的方法, 把SubToggle替换成KWEnum, 具体参数可以参考[https://github.com/JasonMa0012/LWGUI?tab=readme-ov-file#kwenum](url)

**Comment by lokyeye** [comment]
大佬这个参考点开是没有的！
![Uploading QQ截图20240409000451.png…]()

**Comment by JasonMa0012** [comment]
你这个图片也是没有的, 等上传完再点提交

**Comment by lokyeye** [comment]
![QQ截图20240409000451](https://github.com/JasonMa0012/LWGUI/assets/34017903/714308c0-75ec-4904-a813-1d4a292742ed)
