### ISSUE TITLE
Ase可以利用RenderQueue来控制材质球是透明的还是不透的吗？

### ISSUE THREAD

**Issue by lokyeye** [JasonMa0012/LWGUI#47]
大佬！可以教教[Preset(LWGUI BlendModePreset)] BlendMode ("Blend Mode Preset"float)=0
是否可以用在ASE上面让urp管线的Ase材质能选择透明不透明！

**Comment by JasonMa0012** [comment]
可以

**Comment by lokyeye** [comment]
可以来个图文教程吗！感恩大佬！

**Comment by JasonMa0012** [comment]
和之前的方法一样, 新建一个float parameter, 打开auto register, 然后填入你需要的drawer

**Comment by JasonMa0012** [comment]
自行举一反三, 有疑问多看生成的代码

**Comment by lokyeye** [comment]
主要是ASE内URP的lit控制透明不透明是通过Blend Mode里面的Src和Dst，按着测试的结果应该是不透明Src给1 Dst给4，透明的Src给2 Dst给8，因为是小美术真的有点看不懂这个代码！感恩

**Comment by JasonMa0012** [comment]
那你可能需要新建一个Preset, 把Src和Dst改成你想要的值就行了

**Comment by lokyeye** [comment]
好的！明天试试！感恩大佬！晚安！好梦！

**Comment by lokyeye** [comment]
我尝试了用Float加上Preset(Preset, LWGUI_BlendModePreset)，但是有个问题是他只是控制渲染层不透明2000透明3000，ase实际效果并不对

**Comment by JasonMa0012** [comment]
LWGUI_BlendModePreset需要配合以下代码才有效:

```
[SubToggle(State)] _ZWrite("Z Write", Float) = 1
[SubEnum(State, UnityEngine.Rendering.BlendMode)] _SrcBlend("Src Blend", Float) = 1
[SubEnum(State, UnityEngine.Rendering.BlendMode)] _DstBlend("Dst Blend", Float) = 0

........

        Pass
        {
            Name "ForwardLit"
            Tags
            {
                "LightMode"="UniversalForward"
            }
            
            ZWrite [_ZWrite]
            Blend [_SrcBlend] [_DstBlend]

........

```

**Comment by JasonMa0012** [comment]
确保你自己的ASE生成的结果包含_ZWrite / _SrcBlend / _DstBlend参数, 
如果你的代码里的参数名和LWGUI_BlendModePreset中的不一致, 比如_Src / _Dst, 就需要新建一个BlendModePreset包含_Src / _Dst

**Comment by lokyeye** [comment]
![image](https://github.com/JasonMa0012/LWGUI/assets/34017903/9508701e-22e0-4777-b0ef-f5f1b7b34ebc)
![image](https://github.com/JasonMa0012/LWGUI/assets/34017903/55f9f91a-d09d-40b4-ad0f-dc41a39b03c1)
![image](https://github.com/JasonMa0012/LWGUI/assets/34017903/04a1f990-c814-4177-a4d0-00b0595064ef)
![image](https://github.com/JasonMa0012/LWGUI/assets/34017903/071cb779-c115-478f-bbb5-2b89f7de8fdc)
![image](https://github.com/JasonMa0012/LWGUI/assets/34017903/a758ddbd-7b1d-4a94-87b1-bf6261d231d9)
大佬你看看是否是这样

**Comment by JasonMa0012** [comment]
![image](https://github.com/JasonMa0012/LWGUI/assets/39983625/9b442320-58eb-450e-9a9f-c97e0c63be14)
RGB和Alpha应该相同.

![image](https://github.com/JasonMa0012/LWGUI/assets/39983625/048664a5-26f1-439b-a614-3bb507b151ea)
类型应该是Parameter.

**Comment by lokyeye** [comment]
![image](https://github.com/JasonMa0012/LWGUI/assets/34017903/6147645b-88a1-4498-baea-045f995dc724)好像没看到Parameter

**Comment by JasonMa0012** [comment]
Property

**Comment by lokyeye** [comment]
okok！谢谢！已经调好了！
