### ISSUE TITLE
[Tex(BaseGroup, _Float)]在2.0中只有颜色和Channel生效，float和range是不生效的

### ISSUE THREAD

**Issue by falseeeeeeeeee** [JasonMa0012/LWGUI#48]
![Snipaste_2024-04-26_17-56-55](https://github.com/JasonMa0012/LWGUI/assets/58615333/0eadcc90-ac07-478c-8a5e-20f1c63cf8f8)

用的是beta2.0那个包
我在是用[Tex(BaseGroup, _Float)]的时候，只有Color和Channel生效，float和range是不生效的

**Comment by JasonMa0012** [comment]
和range一起用会有些bug, 暂未支持

**Comment by JasonMa0012** [comment]
刚刚提交了一下, 支持float, 但是没有Range

**Comment by falseeeeeeeeee** [comment]
辛苦大大，可以了~
![image](https://github.com/JasonMa0012/LWGUI/assets/58615333/301bb90b-a136-4148-8ee7-eae6c48b1feb)
我每次选中材质球的时候会弹出一个警告，报错如下
Unable to find style 'ToolbarSearchTextFieldPopup' in skin 'DarkSkin' Layout
UnityEngine.GUIStyle:op_Implicit (string)
LWGUI.Helper:get_guiStyles_ToolbarSearchTextFieldPopup () (at Assets/ExternPlugins/LightWeightShaderGUI/Editor/Helper/Helper.cs:235)
LWGUI.Helper:DrawSearchField (UnityEngine.Rect,LWGUI.LWGUIMetaDatas) (at Assets/ExternPlugins/LightWeightShaderGUI/Editor/Helper/Helper.cs:709)
LWGUI.LWGUI:OnGUI (UnityEditor.MaterialEditor,UnityEditor.MaterialProperty[]) (at Assets/ExternPlugins/LightWeightShaderGUI/Editor/LWGUI.cs:47)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

我不懂GUI的代码，我问GPT，我也不知道对不对，在Helper中将原来的改为了下面的，希望后续大大做的更好，辛苦辛苦
![image](https://github.com/JasonMa0012/LWGUI/assets/58615333/4d3af387-f090-416c-a095-f315e839f8cc)
