### ISSUE TITLE
使用RampHelper會一直新增ScriptableObject<GradientObject>導致內存瓶頸

### ISSUE THREAD

**Issue by Teeinn0730** [JasonMa0012/LWGUI#52]
在TextureProperty前新增[Ramp]
把鼠標放在材質球面板上就可以看到 Profiler / Memory / Scene Objects 持續增加

**Comment by JasonMa0012** [comment]
试下最新的2.x分支

**Comment by Teeinn0730** [comment]
解決了，感謝大大!
另外我的版本是2022.1.24f1，LwguiGradient.cs中使用的AnimationCurve.ClearKeys()方法並不存在
目前是將Clear()函式整個註解掉 不影響使用

**Comment by JasonMa0012** [comment]
编译报错已修复
