### ISSUE TITLE
New Ramp gradient editor doesn't have "Fixed" mode option

### ISSUE THREAD

**Issue by Relecto** [JasonMa0012/LWGUI#70]
**Describe the bug / 描述你遇到的Bug**

Old version of LWGUI used the default gradient editor which has an option to set gradient mode to "Fixed", this is very useful to create cel shading ramp maps.
The new version, while being absolutely amazing, doesn't have this option.
It causes a problem when you try to open a gradient created in older version in LWGUI, it resets all keys to smooth interpolation

**Work around is to select all keys, right-click any key and set mode of both tangents to constant.** You will get a fixed gradient:
![image](https://github.com/user-attachments/assets/ac0e239c-a351-4b81-893d-56064bb2e1dd)

**To reproduce**
1. Create a a RampMap in a version of LWGUI with old gradient editor
2. Update LWGUI
3. Try to edit the same rampmap

**Screenshots / 截图**
Old gradient editor with mode set to fixed:
![Old version](https://github.com/user-attachments/assets/af9f0e06-0618-4aeb-b860-968e2b9d16ec)

**Unity Version / Unity版本**
 6000.0.24f1
 
Perhaps it is not something that needs to be fixed, but I thought I will leave it here in case someone else runs into this problem 

Thank you for your work on LWGUI!

**Comment by JasonMa0012** [comment]
Details have been added to the documentation
