### ISSUE TITLE
希望能在禁用一些 Pass 的同时开启一些 Pass, 实现 Pass 切换.

### ISSUE THREAD

**Issue by pengjiaxusz** [JasonMa0012/LWGUI#71]
希望有个刚好反着操作的 [[PassSwitchDecorator](https://github.com/JasonMa0012/LWGUI/blob/92338d4ca66eeeb228cecb435ba634f81e5d1819/Editor/ShaderDrawer.cs#L1498C15-L1498C34)], 刚好在禁用一些 Pass 的同时启用一些 Pass.

使用起来更方便, 更灵活的 Pass 配置, 不用让使用者先去开启一个开关再去关闭一个开关来实现 Pass 切换.

类似下面的感觉:
```Java
[Main(一键切换 Pass off, on)]
[PassSwitchDecorator(启用的 Pass)]
[PassDisableDecorator(禁用的 Pass)]
_Group("一键切换 Pass", Float) = 0
```
代码截图, 复制于 [PassSwitchDecorator](https://github.com/JasonMa0012/LWGUI/blob/92338d4ca66eeeb228cecb435ba634f81e5d1819/Editor/ShaderDrawer.cs#L1498C15-L1498C34), 就修改了 `prop.floatValue > 0` 到 `prop.floatValue == 0`:

![image](https://github.com/user-attachments/assets/4ef8ef94-a0d8-4ddd-9c35-40aa50aa858b)

**Comment by JasonMa0012** [comment]
这个功能可以通过切换Preset实现

**Comment by pengjiaxusz** [comment]
Preset 是指这样做的吗, 开始是打算做到 Main 的勾选框上面去的.

```Java
[Main(一键切换 Pass off, on)] _Group("一键切换 Pass", Float) = 0
[Preset(Prest, Preset)] _Preset("Preset", Float) = 0 // 新建两个预设, 使用下拉列表调换下面两个属性的值.
[HideInInspector][PassSwitchDecorator(E1, E2)] _EnablePasses("EnablePasses", Float) = 0
[HideInInspector][PassSwitchDecorator(D1, D2, D3)] _DisablePasses("DisablePasses", Float) = 1
```

Preset 是挺强大的, 不过用来做这种简单的 Pass 切换感觉有点复杂. 每加一个切换就得多设计一些属性, 还得额外管配置. 有点纠结要不要用这个方式, 可能更新插件时源码复制一段 PassSwitchDecorator 改下判断条件会轻松点.

**Comment by JasonMa0012** [comment]
对的.   
需求多种多样, 不可能给每种需求单独写个Drawer, 尽量使用现有功能.  
如果确实有必要, 你可以自己修改.

**Comment by JasonMa0012** [comment]
1.21.0支持使用Main()和SubToggle()切换Preset了

**Comment by pengjiaxusz** [comment]
刚刚偶然提取远程才看到新增的 Preset 禁用启用 Pass, 看得我有点兴奋, 马上试了起来.
现在是真的非常方便了, 只需要填 LightMode 名字就行, 打算全部改用 Preset 禁用启用了.
非常感谢, 没想到您把这个便利的功能实现了, 非常好用🌹
