### ISSUE TITLE
[建议]对Group关键字支持与或非

### ISSUE THREAD

**Issue by Tollainmear** [JasonMa0012/LWGUI#9]
希望能够支持根据一个或多个判断条件（Group）显示/隐藏参数的功能

比如某个参数(如Intensity)希望能够在不同的KeyEnum条件下复用(`||`或逻辑)，或通某个参数的显示需要满足过多个条件(`&&`并逻辑)

痛点在于，切换KeyEnum之后，在上一KeyEnum下Check但已不渲染的subtoggle仍然会使仅适用于上一KeyEnum的参数被渲染

**Comment by JasonMa0012** [comment]
未来酌情添加, 目前可以通过以下方法绕开:
- 用不同Property分别对应不同Keyword
- 对于更复杂的条件在Tooltip中注释

**Comment by JasonMa0012** [comment]
已支持或: https://github.com/JasonMa0012/LWGUI/commit/1c2b54c6ab48acb343526501b6daf655990edb35

**Comment by JasonMa0012** [comment]
参考ShowIf()
